name: Notify Discord on Push

on:
  push:
    branches:
      - main  # Cambia esto al nombre de la rama que deseas monitorear

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        uses: actions/http-client@v1
        with:
          url: 'https://discord.com/api/webhooks/1296316724009898096/GqXIpSuukjmQvBD_ia1PUA_LGkLfMb-UP_IjW5lyZOIp3IGfbX_jWtv-HltIoz2tq7dv'  # Reemplaza con la URL de tu webhook de Discord
          method: 'POST'
          headers: '{"Content-Type": "application/json"}'
          body: '{"content": "Nuevo commit en FoodShared: ${{ github.event.head_commit.message }}"}'
